'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace UI

	Partial Public Class Page

		'''<summary>
		'''TitleDisplay control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents TitleDisplay As Global.N2.Web.UI.WebControls.Display

		'''<summary>
		'''TextLiteral control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents TextLiteral As Global.System.Web.UI.WebControls.Literal
	End Class
End Namespace
