'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Site

	'''<summary>
	'''Head1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

	'''<summary>
	'''head control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

	'''<summary>
	'''form2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents form2 As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''N2SiteMap control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents N2SiteMap As Global.System.Web.UI.WebControls.SiteMapDataSource

	'''<summary>
	'''Menu1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Menu1 As Global.System.Web.UI.WebControls.Menu

	'''<summary>
	'''Path control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Path As Global.System.Web.UI.WebControls.SiteMapPath

	'''<summary>
	'''content control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents content As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
