//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2.Edit {
    
    
    public partial class Default {
        
        /// <summary>
        /// NavigationPlugins control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::N2.Edit.Web.UI.Controls.ToolbarPluginDisplay NavigationPlugins;
        
        /// <summary>
        /// PreviewPlugins control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::N2.Edit.Web.UI.Controls.ToolbarPluginDisplay PreviewPlugins;
        
        /// <summary>
        /// OperationsPlugins control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::N2.Edit.Web.UI.Controls.ToolbarPluginDisplay OperationsPlugins;
        
        /// <summary>
        /// OptionsPlugins control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::N2.Edit.Web.UI.Controls.ToolbarPluginDisplay OptionsPlugins;
    }
}
