//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2.TemplateWeb.Uc {
    
    public partial class UCEditorTest {
        protected System.Web.UI.WebControls.DropDownList year;
        protected System.Web.UI.WebControls.DropDownList month;
        protected System.Web.UI.WebControls.DropDownList day;
    }
}
