//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo {
    
    public partial class Register {
        protected System.Web.UI.WebControls.Literal ltTitle;
        protected System.Web.UI.WebControls.Literal ltText;
        protected System.Web.UI.WebControls.PlaceHolder plhSubmit;
        protected System.Web.UI.WebControls.Label lblEmail;
        protected System.Web.UI.WebControls.TextBox txtEmail;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        protected System.Web.UI.WebControls.Label lblPraise;
        protected System.Web.UI.WebControls.TextBox txtPraise;

        protected System.Web.UI.WebControls.TextBox txtPassword; 
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
