//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Toolbar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Toolbar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Toolbar", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string copy_Title {
            get {
                return ResourceManager.GetString("copy.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy item including sub-items.
        /// </summary>
        internal static string copy_ToolTip {
            get {
                return ResourceManager.GetString("copy.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string delete_Title {
            get {
                return ResourceManager.GetString("delete.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete item including sub-items.
        /// </summary>
        internal static string delete_ToolTip {
            get {
                return ResourceManager.GetString("delete.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string edit_Title {
            get {
                return ResourceManager.GetString("edit.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit selected item.
        /// </summary>
        internal static string edit_ToolTip {
            get {
                return ResourceManager.GetString("edit.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string filemanager_Title {
            get {
                return ResourceManager.GetString("filemanager.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file manager.
        /// </summary>
        internal static string filemanager_ToolTip {
            get {
                return ResourceManager.GetString("filemanager.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string move_Title {
            get {
                return ResourceManager.GetString("move.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cut selected item (select destination and paste to move).
        /// </summary>
        internal static string move_ToolTip {
            get {
                return ResourceManager.GetString("move.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string new_Title {
            get {
                return ResourceManager.GetString("new.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create new item below selected item.
        /// </summary>
        internal static string new_ToolTip {
            get {
                return ResourceManager.GetString("new.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string paste_Title {
            get {
                return ResourceManager.GetString("paste.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paste the item in memory.
        /// </summary>
        internal static string paste_ToolTip {
            get {
                return ResourceManager.GetString("paste.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string search_Title {
            get {
                return ResourceManager.GetString("search.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search items.
        /// </summary>
        internal static string search_ToolTip {
            get {
                return ResourceManager.GetString("search.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string settings_Title {
            get {
                return ResourceManager.GetString("settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        internal static string settings_ToolTip {
            get {
                return ResourceManager.GetString("settings.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string table_Title {
            get {
                return ResourceManager.GetString("table.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabular navigation.
        /// </summary>
        internal static string table_ToolTip {
            get {
                return ResourceManager.GetString("table.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string tree_Title {
            get {
                return ResourceManager.GetString("tree.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hierarchical navigation.
        /// </summary>
        internal static string tree_ToolTip {
            get {
                return ResourceManager.GetString("tree.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string versions_Title {
            get {
                return ResourceManager.GetString("versions.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous versions.
        /// </summary>
        internal static string versions_ToolTip {
            get {
                return ResourceManager.GetString("versions.ToolTip", resourceCulture);
            }
        }
    }
}
