//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2.Edit.Membership
{

	public partial class New
	{
        protected System.Web.UI.WebControls.CreateUserWizard createUserWizard;
        protected System.Web.UI.WebControls.CreateUserWizardStep cuwsCreate;
    }
}
