SELECT [ID]
      ,[Name]
      ,[ZoneName]
      ,[ParentID]
      ,[Type]
      ,[Title]
      ,[SortOrder]
      ,[Created]
      ,[Updated]
      ,[Published]
      ,[Expires]
      ,[Visible]
      ,[VersionOfID]
      ,[SavedBy]
  FROM [dbo].[n2Item]
  
  SELECT [ID]
      ,[ItemID]
      ,[Name]
      ,[BoolValue]
      ,[IntValue]
      ,[DateTimeValue]
      ,[DoubleValue]
      ,[StringValue]
      ,[Value]
      ,[Type]
  FROM [dbo].[n2Detail]
  
  SELECT [ID]
      ,[ItemID]
      ,[Role]
  FROM [dbo].[n2AllowedRole]