//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2.Templates.UI.Parts {
    
    
    /// <summary>
    /// Statistics class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class Statistics {
        
        /// <summary>
        /// lblPages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
		protected global::System.Web.UI.WebControls.Label lblPages;
		protected global::System.Web.UI.WebControls.Label lblServed;
		protected global::System.Web.UI.WebControls.Label lblItems;
		protected global::System.Web.UI.WebControls.Label lblVersionsRatio;
		protected global::System.Web.UI.WebControls.Label lblChangesLastWeek;
        
        /// <summary>
        /// rptLatestChanges control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptLatestChanges;
    }
}
