//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2.Edit.Security {
    
    public partial class Default {
        protected System.Web.UI.WebControls.LinkButton btnSave;
        protected System.Web.UI.WebControls.HyperLink hlCancel;
        protected System.Web.UI.WebControls.CustomValidator cvSomethingSelected;
        protected System.Web.UI.WebControls.CheckBoxList cblAllowedRoles;
        protected System.Web.UI.WebControls.ObjectDataSource odsRoles;
    }
}
