<%@ Page Theme="Theme1" MasterPageFile="~/DefaultMasterPage.Master" Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="N2.TemplateWeb.Default" %>
<%@ OutputCache CacheProfile="DefaultCache" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

[[<%= System.Web.SiteMap.CurrentNode %>]]
[[<%= CurrentPage.ID %>]]
  <%--  
    <h1><%= CurrentPage.Title %></h1>
    
    <n2:H1 runat="server" Text="<%$ CurrentPage: Title %>" />
    
    <h1><asp:Literal runat="server" Text="<%$ CurrentPage: Title %>" /></h1>
    
    <n2:Display runat="server" PropertyName="Title" />
    
    <n2:EditableDisplay runat="server" PropertyName="Title" />

	<asp:HyperLink Text="<%$ CurrentPage: MyLabel %>" NavigateUrl="<%$ CurrentPage: MyFile %>" runat="server" />
	
	<a href="<%= CurrentPage.MyFile %>"><%= CurrentPage.MyLabel %></a>
    
    <asp:HyperLink ID="HyperLink1" runat="server" />
    
	<n2:ItemDataSource ID="Level1Items" runat="server" Path="/" />
	<asp:DataGrid DataSourceID="Level1Items" runat="server" />
    
    <n2:Zone ZoneName="RightColumn" runat="server" />
    
    <n2:DroppableZone ZoneName="RightColumn" runat="server" />--%>
    
    <n2:DraggableToolbar runat="server" />
    <p><b>The N2DevelopmentWeb project is mess caused by incremental development and testing of new features in N2. You shouldn't really look at it. Please look at the examples instead.</b></p>
    
    <N2:EditableDisplay PropertyName="Text" runat="server" />
    <hr />
    <%= System.Threading.Thread.CurrentThread.CurrentCulture.Name %><%= DateTime.Now %>
    <a href="#" onclick="$('html').load('/ html');">RELOAD</a>
    <style>
        td{vertical-align:top;}
        .content{width:500px;}
    </style>
    <table><tr><td>
    <div style="border:dotted 1px blue;width:200px;clear:right;">
       <n2:DroppableZone id="Left" ZoneName="Left" runat="server" />
    </div>
    </td><td>

[<a href="<%= CurrentPage.FileUrl %>"><%= CurrentPage.FileUrl %></a>]

    <div class="content">
    <!--
        N2.Factory.UrlParser.StartPage <%= N2.Context.UrlParser.StartPage %><br />
        HttpContext.Current.Request.Url.Host <%= HttpContext.Current.Request.Url.Host %><br />
        <hr />
        N2.Factory.CurrentPage: <%= N2.Context.CurrentPage %><br />
        Request.RawUrl: <%= Request.RawUrl %><br />
        -->
        <n2:DroppableZone ZoneName="Content" runat="server" />
    </div>
    </td><td>
    <div style="border:dotted 1px green;width:200px;clear:right;">
       <n2:DroppableZone id="MainDataContainer" ZoneName="Right" runat="server" Path="<%$ CurrentPage: ZonePath %>" />
    </div>

    </td></tr></table>
    <!--
    <hr />
     - saved: [<%= CurrentPage.Created %>]
     - updated: [<%= CurrentPage.Updated %>]
     - newed: [<%= DataBinder.Eval(CurrentPage, "NewedDate") %>]
        [<%= CurrentPage.FileUrl %>]
        [<%= CurrentPage.MyItem %>]
        [<%= CurrentPage.MyFile %>]
    -->
    <hr />
    <N2:ItemDataSource ID="ids" runat="server" />
    <asp:GridView ID="gvChildren" runat="server" DataSourceID="ids" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" AutoGenerateColumns="false" DataKeyNames="ID">
        <EditRowStyle BackColor="#C0FFC0" />
        <SelectedRowStyle BackColor="#FFFFC0" />
        <Columns>
            <asp:HyperLinkField DataTextField="Title" DataNavigateUrlFields="Url" />
            <asp:BoundField DataField="Name" />
        </Columns>
    </asp:GridView>

</asp:Content>