//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace N2.TemplateWeb {
    
    public partial class FilterTest {
        protected System.Web.UI.WebControls.GridView gvAccess;
        protected System.Web.UI.WebControls.GridView GridView4;
        protected System.Web.UI.WebControls.GridView GridView1;
        protected System.Web.UI.WebControls.GridView GridView2;
        protected System.Web.UI.WebControls.GridView GridView3;
    }
}
